- name: install prometheus in ubuntu
  apt:
    name:
      - prometheus
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install prometheus requisites for centos
  tags: centos, snapd, epel-release
  yum:
    name:
      - epel-release
      - snapd
    state: latest
  when: ansible_distribution == "CentOS"

- name: enabling sockets for centos
  tags: snapd, centos
  command: systemctl enable --now snapd.socket
  when: ansible_distribution == "CentOS"

- name: finishing installation of prometheus in centos
  tags: centos, prometheus
  command: snap install prometheus --classic
  when: ansible_distribution == "CentOS"
