- name: install php for ubuntu
  apt:
    name: 
      - apache2
      - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  
- name: install mariadb package for ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
  
- name: install php for centos
  dnf:
    name: 
      - php
      - httpd
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"
  
- name: install mariadb package for centos
  yum:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "CentOS"
  
- name: "Mariadb- Restarting/Enabling"
  service:
    name: mariadb
    state: restarted
    enabled: true
